---
name: TTY
highlighter: pygments
relative_permalinks: false
baseurl: "/tty"
google_analytics_id: UA-31255537-2
plugins:
  - jekyll-assets
  - bourbon
  - font-awesome-sass
assets:
  compress:
    css: sass
    js: uglifier
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
exclude: [components, Rakefile, Gemfile, Gemfile.lock, README.md]
